### ISSUE TITLE
I made a duplicate by mistake

### ISSUE THREAD

**Issue by aloisdg** [alebcay/awesome-shell#136]
Hello,

I looked for an awesome-bash. I couldn't find one so I made one.
You can see it [here](https://github.com/awesome-lists/awesome-bash/). I looked for scripts and found yours.

Now, we can do two things. I can create a PR with my links or you can switch your bash specific links in mine. If we choose the second one, you are going to be the awesome-list for every kind of shell (as your name suggest).

What do you think?

**Comment by alebcay** [comment]
I was planning to move Bash stuff out at some point (as I have been planning to do with fish and zsh stuff).

**Comment by aloisdg** [comment]
@alebcay Nice. Since I really like what you build here, I would love to give you the `collaborator` status on `awesome-bash`. Also, it will be easiest to manage it.  What do you think?

**Comment by alebcay** [comment]
Sure, no problem.

**Comment by aloisdg** [comment]
Done. Which part should we move? All awesome-bash section's sub sections like Customization or Games?

**Comment by alebcay** [comment]
I would consider anything that is bash-specific to be eligible for moving; anything that's POSIX-compliant or compatible with other shells can stay here (e.g. some games, I would think). Package managers and bash-specific test frameworks can also be moved.

**Comment by aloisdg** [comment]
I created a `develop` branch with a [first draft of the merge](https://github.com/awesome-lists/awesome-bash/blob/develop/readme.md). If I missed something important, feel free to add it.

**Comment by alebcay** [comment]
Looks alright, although I am planning to keep some of the links you moved on my page (e.g. `bocker`, `bashttpd`, and `sshrc`). The rationale is that while the tools are written as a Bash script, you don't need to be running bash to be using them, where as with some other items (e.g. `commacd`, `sexy-bash-prompt`) are only applicable to zsh.

Also, I plan to keep anything related to not exclusively Bash (e.g. compatible with Zsh as well), except for some things under "Customization" (e.g. color schemes can stay, but things like `oh-my-git` would probably be better off in respective `awesome-bash` and `awesome-zsh` repositories`).

**Comment by aloisdg** [comment]
Ok go ahead. :smile:

**Comment by aloisdg** [comment]
@alebcay I am going to do the [merge](https://github.com/awesome-lists/awesome-bash/pull/2). Anything to add? (I will close #136 after)

**Comment by alebcay** [comment]
Looks fine.
