### ISSUE TITLE
Latest Pull Requests are failing Travis/CI

### ISSUE THREAD

**Issue by frosencrantz** [alebcay/awesome-shell#387]
Hi @alebcay 

The latest pull requests are failing in travis-ci.  Some of links have moved or disappeared.

It was not clear from your guidelines how you prefer these to be fixed:
   - You'll fix these
   - Fix them in our pull requests
   - Create a separate request to fix

**Comment by labbots** [comment]
I see the similar issue with my pull request. Error seams to be because of SSL certificate issue.

```
[L415]  https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) 
```

**Comment by alebcay** [comment]
Thanks for your concerns, I apologize for not getting to this sooner. The CI issues should be resolved now. Generally if the failure is unrelated to the specific contribution, I will fix it myself.

**Comment by labbots** [comment]
Thanks for letting know.. @alebcay.
