### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [alebcay/awesome-shell#60]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by alebcay** [comment]
It sounds like a great idea. I'd like to note that there are already such organizations that exist solely for this purpose. Thus, I would rather keep my repository where it is. However, you are more than welcome to fork this and update it at will, or if you are willing to grant permissions, I am willing to fork this into your organization and keep it updated myself.

**Comment by jhermann** [comment]
This obviously calls for an Organization with Lists of Awesome Organizations with Lists of Awesome Things. :grin:

**Comment by jeffreyjackson** [comment]
woohoo, @alebcay just tell me who to make admins, and I'll have it ready for you when you want to transfer.

**Comment by alebcay** [comment]
@jeffreyjackson, if you could add me to the organization with permission to fork, I will go ahead and fork this into the organization. Note that I am going to maintain a fork there (and keep it up to date), but I do not intend to move this repo itself.
